### ISSUE TITLE
Add autoDocstring to recommended extensions

### ISSUE THREAD

**Issue by SaschaCowley** [nvaccess/vscode-nvda#13]
The [autoDocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) extension allows automatic generation of docstrings for methods, and supports Sphinx typeless style out of the box. We should add this to the recommended extensions, and add the recommended settings to the workspace config.

**Comment by seanbudd** [comment]
Agreed, wasn't aware of the no-types option which fixed the issues I was having with it
