### ISSUE TITLE
Improve instructions for setting up.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/vscode-nvda#3]
It's not clear how to set up a project/workspace that uses this config. Some more detailed instructions, could help to encourage people to use it. Perhaps highlighting a few features in VSCode that this config influences and why it's helpful.

**Comment by LeonarddeR** [comment]
Would you like that in the main readme of the NVDA repo?

**Comment by feerrenrut** [comment]
I think that's a good place for it. If the readme gets too big we could always add a docs folder.

**Comment by seanbudd** [comment]
Instructions for this is now mentioned here: https://github.com/nvaccess/nvda/blob/8fb8ffcaba3950b1e4ca7b58e165267fc5369eb9/projectDocs/dev/createDevEnvironment.md
